FROM ubuntu:16.04

ENV REFRESHED_AT 2018-06-05

RUN apt-get -yqq update
RUN apt-get -yqq install wget

VOLUME  [ "/var/lib/tomcat7/webapps" ]
WORKDIR /var/lib/tomcat7/webapps

ENTRYPOINT [ "wget" ]
CMD [ "-?" ]
